services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: videogames_db
    ports:
      - "5432:5432"

  data_loader:
    build:
      context: .
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: videogames_db
      DB_USER: user
      DB_PASSWORD: password
    command: ["python", "dataset/game_info.py"]

  api:
    build:
      context: .
    depends_on:
      - db
      - data_loader
    environment:
      DB_HOST: db
      DB_NAME: videogames_db
      DB_USER: user
      DB_PASSWORD: password
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
